<a href="https://colab.research.google.com/github/mahmudul58/Python-and-AI-ML-Fundamentals/blob/main/Pandas_practice_problem_and_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **📝 Task 1**

- Create a **Pandas Series** from the list `[10, 20, 30, 40, 50]`. Print the Series, its index, values, datatype, and size.
- Create a **DataFrame** using lists of *Name*, *Age*, and *City* containing at least 4 rows of data.

In [2]:
import pandas as pd

list=[10,20,30,40,50]

series=pd.Series(list)
print(f"Series;\n{series}")
print(f"Index: {series.index}")
print(f"Values:{series.values}")
print(f"Data type:{series.dtype}")
print(f"size:{series.size}")

Series;
0    10
1    20
2    30
3    40
4    50
dtype: int64
Index: RangeIndex(start=0, stop=5, step=1)
Values:[10 20 30 40 50]
Data type:int64
size:5

In [ ]:
people = [
    ["Karim", 24, "Dhaka"],
    ["Fatima", 29, "Chittagong"],
    ["Tanvir", 22, "Sylhet"],
    ["Nusrat", 31, "Rajshahi"],
]
df=pd.DataFrame(people,columns=['Name','Age','City'],index=[1,2,3,4])
df

     Name  Age        City
1   Karim   24       Dhaka
2  Fatima   29  Chittagong
3  Tanvir   22      Sylhet
4  Nusrat   31    Rajshahi

### **📝 Task 2**

- Using any DataFrame, write code to print the **number of rows and columns**, **column data types**, **memory usage** (using `.info()`), and **summary statistics** (`.describe()`).

In [ ]:
student_df=pd.read_csv('sample_data/student_data.csv')
print(student_df.info())
print(f"\nSummary statistics: \n{student_df.describe()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.5+ KB
None

Summary statistics:
       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

### **📝 Task 3**

- Create a DataFrame using the dictionary below:

```python
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}
```
- Print `.columns` and `.index`.
- Access a **single column** and **one full row**.

In [ ]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}
data_frame=pd.DataFrame(data)
print(f"Data frame:\n {data_frame}")
print(f"\nColumns:\n {data_frame.columns}")
print(f"\nIndex:\n {data_frame.index}")
col=data_frame['Product']
print(f"\nAccess a Single column:\n{col}")

row=data_frame.loc[1]
print(f"\nAccess a Single row:\n{row}")

Data frame:
   Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

Columns:
 Index(['Product', 'Price', 'Quantity'], dtype='object')

Index:
 RangeIndex(start=0, stop=4, step=1)

Access a Single column:
0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: object

Access a Single row:
Product     Book
Price         50
Quantity      60
Name: 1, dtype: object

### **📝 Task 4**

- Using the same dictionary DataFrame, access specific cells:
  - The element at the **2nd row**, `'Product'` column.
  - Elements from **index 1 to 3** in `'Price'` & `'Quantity'` columns.

In [ ]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}
data_frame=pd.DataFrame(data)
print(data_frame.loc[1,'Product'])
print()
data_frame.loc[1:3,['Price','Quantity']]

Book

   Price  Quantity
1     50        60
2      5       200
3      7       150

### **📝 Task 5**

- Set the `'Product'` column as index.
- Access `'Book'` row using `.loc`.
- Change `'Pencil'` quantity to `200`.

In [5]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}
data_frame=pd.DataFrame(data)
data_frame=data_frame.set_index("Product")
print(data_frame)
print()

print(data_frame.loc['Book'])

data_frame.loc['Pencil','Quantity']=200
data_frame

         Price  Quantity
Product
Pen         10       100
Book        50        60
Eraser       5       200
Pencil       7       150

Price       50
Quantity    60
Name: Book, dtype: int64

         Price  Quantity
Product
Pen         10       100
Book        50        60
Eraser       5       200
Pencil       7       200

### **📝 Task 6**

- Perform **Arithmetic operations** on columns: Create `'Total_Value' = Price * Quantity`.
- Find the **total sum**, **average** of `'Price'`, and find the product with the **maximum quantity**.

In [16]:
from numpy import average
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}
data_frame=pd.DataFrame(data)
data_frame['Total_Value']=data_frame.loc[:,'Price']*data_frame.loc[:,'Quantity']
print(f"data frame:\n{data_frame}\n")
# print()

total_sum=sum(data_frame.loc[:,'Price'])
print(f"Total sum: {total_sum}\n")

total_average=average(data_frame.loc[:,'Price'])
print(f"Total average: {total_average}\n")

# product_max_id=data_frame['Quantity'].idxmax()
print(f"\nProduct with Maxium Quantity: {data_frame.loc[data_frame['Quantity'].idxmax(),'Product']}\n")

data frame:
  Product  Price  Quantity  Total_Value
0     Pen     10       100         1000
1    Book     50        60         3000
2  Eraser      5       200         1000
3  Pencil      7       150         1050

Total sum: 72

Total average: 18.0


Product with Maxium Quantity: Eraser

### **📝 Task 7**

- Create a DataFrame of employees with columns `'Name'`, `'Department'`, and `'Salary'`. Sort it by `'Salary'` in ascending order and by `'Name'` in descending order.
- Create a DataFrame of 8 students with columns `'Name'` and `'Score'`. Filter and print students with `Score > 60` and those with `Score < 40`.

In [20]:
data = {
    'Name': ['Rahim', 'Karim', 'Fatima', 'Tanvir'],
    'Department': ['Account', 'HR', 'Finance', 'IT'],
    'Salary': [35000, 30000, 40000, 45000]
}

df = pd.DataFrame(data)

print(df)
print()
df.sort_values(['Name','Salary'],ascending=[1,0])

     Name Department  Salary
0   Rahim    Account   35000
1   Karim         HR   30000
2  Fatima    Finance   40000
3  Tanvir         IT   45000

     Name Department  Salary
2  Fatima    Finance   40000
1   Karim         HR   30000
0   Rahim    Account   35000
3  Tanvir         IT   45000

In [23]:
data = {
    'Name': ['Ahnaf', 'Mehjabin', 'Zayan', 'Inshirah', 'Tahsin', 'Areeba', 'Fahim', 'Nafisa'],
    'Score': [55, 92, 38, 95, 28, 74, 50, 82]
}

df = pd.DataFrame(data)

print(df)
print()
filtered_student=df.loc[(df['Score']>60) | (df['Score']<40)]

filtered_student

       Name  Score
0     Ahnaf     55
1  Mehjabin     92
2     Zayan     38
3  Inshirah     95
4    Tahsin     28
5    Areeba     74
6     Fahim     50
7    Nafisa     82

       Name  Score
1  Mehjabin     92
2     Zayan     38
3  Inshirah     95
4    Tahsin     28
5    Areeba     74
7    Nafisa     82